apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: backstage
  namespace: argocd
spec:
  description: Backstage developer portal
  sourceRepos:
    - https://github.com/luniemma/EDX-BACKTAGE.git
  destinations:
    - namespace: backstage-*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
